CREATE TABLE "AdminIdentity" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "secretHash" TEXT NOT NULL,
  "displayName" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
